name: Publish to Github 

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  schedule:
    - cron: '21 4 * * *'
  push:
    branches: [ master ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ master ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}


jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Copy env to .env
        run: cp env .env
        
      # Builds and pushes docker-compose images
      # https://github.com/pennsignals/publish_docker-compose
      - name: Build and push Docker image
        id: build-and-push
        uses: jochemste/publish_docker-compose@v0.2.7
        with:
          docker_compose: 'docker-compose.yml'
          repo_token: "${{ secrets.UPLOAD_TOKEN }}"
